// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// foodweb
List foodweb(List foodweb_inputs);
RcppExport SEXP _astec_foodweb(SEXP foodweb_inputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type foodweb_inputs(foodweb_inputsSEXP);
    rcpp_result_gen = Rcpp::wrap(foodweb(foodweb_inputs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_astec_foodweb", (DL_FUNC) &_astec_foodweb, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_astec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
