// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// foodweb
List foodweb(List foodweb_inputs);
RcppExport SEXP _astec_foodweb(SEXP foodweb_inputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type foodweb_inputs(foodweb_inputsSEXP);
    rcpp_result_gen = Rcpp::wrap(foodweb(foodweb_inputs));
    return rcpp_result_gen;
END_RCPP
}
// convolve_rcpp
NumericVector convolve_rcpp(NumericVector a, NumericVector b);
RcppExport SEXP _astec_convolve_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// make_average_logbodymass
NumericVector make_average_logbodymass(NumericVector a);
RcppExport SEXP _astec_make_average_logbodymass(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(make_average_logbodymass(a));
    return rcpp_result_gen;
END_RCPP
}
// make_average_logbodymass_within
NumericVector make_average_logbodymass_within(NumericVector a);
RcppExport SEXP _astec_make_average_logbodymass_within(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(make_average_logbodymass_within(a));
    return rcpp_result_gen;
END_RCPP
}
// make_average_logbodymass_matrix
NumericMatrix make_average_logbodymass_matrix(NumericMatrix a);
RcppExport SEXP _astec_make_average_logbodymass_matrix(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(make_average_logbodymass_matrix(a));
    return rcpp_result_gen;
END_RCPP
}
// make_average_logbodymass_matrix3
NumericMatrix make_average_logbodymass_matrix3(NumericMatrix a);
RcppExport SEXP _astec_make_average_logbodymass_matrix3(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(make_average_logbodymass_matrix3(a));
    return rcpp_result_gen;
END_RCPP
}
// make_average_logbodymass_matrix_void
void make_average_logbodymass_matrix_void(NumericMatrix a, NumericMatrix& av);
RcppExport SEXP _astec_make_average_logbodymass_matrix_void(SEXP aSEXP, SEXP avSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type av(avSEXP);
    make_average_logbodymass_matrix_void(a, av);
    return R_NilValue;
END_RCPP
}
// make_average_logbodymass_matrix_void2
void make_average_logbodymass_matrix_void2(NumericMatrix a, NumericMatrix& av);
RcppExport SEXP _astec_make_average_logbodymass_matrix_void2(SEXP aSEXP, SEXP avSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type av(avSEXP);
    make_average_logbodymass_matrix_void2(a, av);
    return R_NilValue;
END_RCPP
}
// multiply_void
void multiply_void(NumericMatrix& a, double k);
RcppExport SEXP _astec_multiply_void(SEXP aSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    multiply_void(a, k);
    return R_NilValue;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _astec_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_astec_foodweb", (DL_FUNC) &_astec_foodweb, 1},
    {"_astec_convolve_rcpp", (DL_FUNC) &_astec_convolve_rcpp, 2},
    {"_astec_make_average_logbodymass", (DL_FUNC) &_astec_make_average_logbodymass, 1},
    {"_astec_make_average_logbodymass_within", (DL_FUNC) &_astec_make_average_logbodymass_within, 1},
    {"_astec_make_average_logbodymass_matrix", (DL_FUNC) &_astec_make_average_logbodymass_matrix, 1},
    {"_astec_make_average_logbodymass_matrix3", (DL_FUNC) &_astec_make_average_logbodymass_matrix3, 1},
    {"_astec_make_average_logbodymass_matrix_void", (DL_FUNC) &_astec_make_average_logbodymass_matrix_void, 2},
    {"_astec_make_average_logbodymass_matrix_void2", (DL_FUNC) &_astec_make_average_logbodymass_matrix_void2, 2},
    {"_astec_multiply_void", (DL_FUNC) &_astec_multiply_void, 2},
    {"_astec_rcpp_hello", (DL_FUNC) &_astec_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_astec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
